### ISSUE TITLE
最新版zipへのリダイレクト もしくは トップページHTML自動生成

### ISSUE THREAD

**Issue by matsuyuki-a** [WWAWing/wwawing.com#1]
最新版にいちいちリンク切り替えるのがめんどくさいので、zipファイルへのリダイレクトページを作るか、index.htmlを自動生成するようにしたいです。

**Comment by enloyable** [comment]
何か、応用できませんか？javascriptだし…
https://www.ipentec.com/document/javascript-change-link-destination-dynamically

**Comment by matsuyuki-a** [comment]
そういえば、これ終わってますね。
最新版が get.wwawing.com で最新のものが固定URLで生成されるので。

**Comment by enloyable** [comment]
閉めてなかっただけか
