### ISSUE TITLE
トップページのカルーセルの枚数とインジケーターの点数が一致しない

### ISSUE THREAD

**Issue by aokashi** [WWAWing/wwawing.com#7]
https://wwawing.com/ の `.carousel-indicators` の要素が4つあるんですが、実際のカルーセルの枚数は3枚になっています。

そのため、実際にトップページを見ると、カルーセル下のインジケーターの4つ目を押しても何も変わらないと思います。

https://github.com/WWAWing/wwawing.com/blob/master/index.html#L138 の辺りは使われてないみたいですので、消してみてはどうでしょうか。

**Comment by matsuyuki-a** [comment]
確かに

**Comment by matsuyuki-a** [comment]
netlify対応分から直します: #6

**Comment by aokashi** [comment]
お願いします 🙇
